version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '0.0.0.0:8080:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    image: daniel1302/vallheru-php:v4.4.9
    command:
      - "-b"
      - "0.0.0.0:9000"
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5-debian
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: vallheru123
      MYSQL_DATABASE: vallheru

volumes:
  mysql_data: